/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongkailiu' at '25/08/16 9:06 PM' with Gradle 2.13
 *
 * @author hongkailiu, @date 25/08/16 9:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
